/* eslint-disable @typescript-eslint/no-require-imports */
import type { Config } from "tailwindcss";
import colors from "./src/styles/colors/index.ts";
import colorsApp from "./src/styles/colors/colorsApp.ts";

const config: Config = {
  important: true,
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        montserrat: ["var(--font-montserrat)", "sans-serif"],
        denkOne: ["var(--font-denkOne)", "sans-serif"],
        gluten: ["var(--font-gluten)", "sans-serif"],
        rugeBoogie: ["var(--font-rugeBoogie)", "sans-serif"],
        handjet: ["var(--font-handjet)", "sans-serif"],
      },
      boxShadow: {
        soft2XSmall: "0px 1.5px 4px -1px rgba(10, 9, 11, 0.18)",
        softExtraSmall:
          "0px 5px 13px -5px rgba(10, 9, 11, 0.05), 0px 2px 4px -1px rgba(10, 9, 11, 0.02)",
        softSmall: "0px 10px 18px -2px rgba(10, 9, 11, 0.07)",
        softMedium:
          "0px 11px 24px -9px rgba(10, 9, 11, 0.14), 0px 0px 3px -1px rgba(10, 9, 11, 0.04)",
        softLarge:
          "0px 32px 33px -15px rgba(10, 9, 11, 0.17), 0px 0px 3px -1px rgba(10, 9, 11, 0.04)",
        hard2XSmall:
          "0px 2px 5px -2px rgba(10, 9, 11, 0.06), 0px 2px 7px 0px rgba(10, 9, 11, 0.05), 0px 0px 0px 1px rgba(10, 9, 11, 0.05)",
        hardExtraSmall:
          "0px 2px 12px -1px rgba(10, 9, 11, 0.1), 0px 2px 2px -1px rgba(10, 9, 11, 0.04), 0px 0px 0px 1px rgba(10, 9, 11, 0.05)",
        hardSmall:
          "0px 6px 16px 0px rgba(10, 9, 11, 0.08), 0px 0px 0px 1px rgba(10, 9, 11, 0.05)",
        hardMedium:
          "0px 16px 24px -6px rgba(10, 9, 11, 0.08), 0px 0px 3px -1px rgba(10, 9, 11, 0.08), 0px 0px 0px 1px rgba(10, 9, 11, 0.05)",
        hardLarge:
          "0px 27px 30px -15px rgba(10, 9, 11, 0.13), 0px 0px 3px -1px rgba(10, 9, 11, 0.04), 0px 0px 0px 1px rgba(10, 9, 11, 0.05)",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
        "linear-gradient-primary":
          "linear-gradient(180deg, #0B61FF 0%, #129EFF 100%)",
      },
      textColor: {
        linearGradientPrimary:
          "linear-gradient(90deg, #0082FB 0%, #00A3FF 100%)",
      },
    },
    colors: {
      content: {
        primary: colorsApp.content.primary,
        secondary: colorsApp.content.secondary,
        tertiary: colorsApp.content.tertiary,
        primaryInverse: colorsApp.content.primaryInverse,
        secondaryInverse: colorsApp.content.secondaryInverse,
        tertiaryInverse: colorsApp.content.tertiaryInverse,
        disabled: colorsApp.content.disabled,
        brand: colorsApp.content.brand,
        link: colorsApp.content.link,
        linkHover: colorsApp.content.linkHover,
        notice: colorsApp.content.notice,
        noticeSecondary: colorsApp.content.noticeSecondary,
        noticeBold: colorsApp.content.noticeBold,
        negative: colorsApp.content.negative,
        negativeSecondary: colorsApp.content.negativeSecondary,
        negativeBold: colorsApp.content.negativeBold,
        positive: colorsApp.content.positive,
        positiveSecondary: colorsApp.content.positiveSecondary,
        positiveBold: colorsApp.content.positiveBold,
        hebe: "#A84537",
      },
      background: {
        bg: colorsApp.background.bg,
        bgInverse: colorsApp.background.bgInverse,
        bgSideBar: colorsApp.background.bgSideBar,
      },
      surface: {
        primary: colorsApp.surface.primary,
        transparent: colorsApp.surface.transparent,
        transparentSecondary: colorsApp.surface.transparentSecondary,
        primaryInverse: colorsApp.surface.primaryInverse,
        primaryHover: colorsApp.surface.primaryHover,
        primaryActive: colorsApp.surface.primaryActive,
        primaryDisabled: colorsApp.surface.primaryDisabled,
        primarySelected: colorsApp.surface.primarySelected,
        secondary: colorsApp.surface.secondary,
        secondaryInverse: colorsApp.surface.secondaryInverse,
        secondaryHover: colorsApp.surface.secondaryHover,
        secondaryActive: colorsApp.surface.secondaryActive,
        secondaryDisabled: colorsApp.surface.secondaryDisabled,
        secondarySelected: colorsApp.surface.secondarySelected,
        tertiaryHover: colorsApp.surface.tertiaryHover,
        tertiaryActive: colorsApp.surface.tertiaryActive,
        tertiaryDisabled: colorsApp.surface.tertiaryDisabled,
        tertiarySelected: colorsApp.surface.tertiarySelected,
        brand: colorsApp.surface.brand,
        brandSecondary: colorsApp.surface.brandSecondary,
        brandHover: colorsApp.surface.brandHover,
        brandActive: colorsApp.surface.brandActive,
        brandDisabled: colorsApp.surface.brandDisabled,
        link: colorsApp.surface.link,
        linkHover: colorsApp.surface.linkHover,
        linkActive: colorsApp.surface.linkActive,
        linkDisabled: colorsApp.surface.linkDisabled,
        linkSelected: colorsApp.surface.linkSelected,
        notice: colorsApp.surface.notice,
        noticeSecondary: colorsApp.surface.noticeSecondary,
        noticeHover: colorsApp.surface.noticeHover,
        noticeActive: colorsApp.surface.noticeActive,
        noticeDisabled: colorsApp.surface.noticeDisabled,
        negative: colorsApp.surface.negative,
        negativeSecondary: colorsApp.surface.negativeSecondary,
        negativeHover: colorsApp.surface.negativeHover,
        negativeActive: colorsApp.surface.negativeActive,
        negativeDisabled: colorsApp.surface.negativeDisabled,
        positive: colorsApp.surface.positive,
        positiveSecondary: colorsApp.surface.positiveSecondary,
        positiveHover: colorsApp.surface.positiveHover,
        positiveActive: colorsApp.surface.positiveActive,
        positiveDisabled: colorsApp.surface.positiveDisabled,
      },
      border: {
        primary: colorsApp.border.primary,
        primaryHover: colorsApp.border.primaryHover,
        primaryActive: colorsApp.border.primaryActive,
        primaryDisabled: colorsApp.border.primaryDisabled,
        primarySelected: colorsApp.border.primarySelected,
        secondary: colorsApp.border.secondary,
        secondaryHover: colorsApp.border.secondaryHover,
        secondaryActive: colorsApp.border.secondaryActive,
        secondaryDisabled: colorsApp.border.secondaryDisabled,
        secondarySelected: colorsApp.border.secondarySelected,
        tertiary: colorsApp.border.tertiary,
        tertiaryHover: colorsApp.border.tertiaryHover,
        tertiaryActive: colorsApp.border.tertiaryActive,
        tertiaryDisabled: colorsApp.border.tertiaryDisabled,
        tertiarySelected: colorsApp.border.tertiarySelected,
        brand: colorsApp.border.brand,
        brandHover: colorsApp.border.brandHover,
        brandActive: colorsApp.border.brandActive,
        brandDisabled: colorsApp.border.brandDisabled,
        notice: colorsApp.border.notice,
        noticeHover: colorsApp.border.noticeHover,
        noticeActive: colorsApp.border.noticeActive,
        noticeDisabled: colorsApp.border.noticeDisabled,
        negative: colorsApp.border.negative,
        negativeHover: colorsApp.border.negativeHover,
        negativeActive: colorsApp.border.negativeActive,
        negativeDisabled: colorsApp.border.negativeDisabled,
        positive: colorsApp.border.positive,
        positiveHover: colorsApp.border.positiveHover,
        positiveActive: colorsApp.border.positiveActive,
        positiveDisabled: colorsApp.border.positiveDisabled,
      },
      transparent: {
        bgPopup: colorsApp.transparent.bgPopup,
      },
      neutral: {
        100: colors.neutral[100],
        200: colors.neutral[200],
        300: colors.neutral[300],
        400: colors.neutral[400],
        500: colors.neutral[500],
        600: colors.neutral[600],
        700: colors.neutral[700],
        800: colors.neutral[800],
        900: colors.neutral[900],
        1000: colors.neutral[1000],
        1100: colors.neutral[1100],
        1200: colors.neutral[1200],
      },
      neutralAlpha: {
        100: colors.neutralAlpha[100],
        200: colors.neutralAlpha[200],
        300: colors.neutralAlpha[300],
        400: colors.neutralAlpha[400],
        500: colors.neutralAlpha[500],
        600: colors.neutralAlpha[600],
        700: colors.neutralAlpha[700],
        800: colors.neutralAlpha[800],
        900: colors.neutralAlpha[900],
        1000: colors.neutralAlpha[1000],
        1100: colors.neutralAlpha[1100],
        1200: colors.neutralAlpha[1200],
        1300: colors.neutralAlpha[1300],
      },
      coolGray: {
        100: colors.coolGray[100],
        200: colors.coolGray[200],
        300: colors.coolGray[300],
        400: colors.coolGray[400],
        500: colors.coolGray[500],
        600: colors.coolGray[600],
        700: colors.coolGray[700],
        800: colors.coolGray[800],
        900: colors.coolGray[900],
        1000: colors.coolGray[1000],
        1100: colors.coolGray[1100],
        1200: colors.coolGray[1200],
      },
      coolGrayAlpha: {
        100: colors.coolGrayAlpha[100],
        200: colors.coolGrayAlpha[200],
        300: colors.coolGrayAlpha[300],
        400: colors.coolGrayAlpha[400],
        500: colors.coolGrayAlpha[500],
        600: colors.coolGrayAlpha[600],
        700: colors.coolGrayAlpha[700],
        800: colors.coolGrayAlpha[800],
        900: colors.coolGrayAlpha[900],
        1000: colors.coolGrayAlpha[1000],
        1100: colors.coolGrayAlpha[1100],
        1200: colors.coolGrayAlpha[1200],
        1300: colors.coolGrayAlpha[1300],
      },
      primary: {
        100: colors.primary[100],
        200: colors.primary[200],
        300: colors.primary[300],
        400: colors.primary[400],
        500: colors.primary[500],
        600: colors.primary[600],
        700: colors.primary[700],
        800: colors.primary[800],
        900: colors.primary[900],
        1000: colors.primary[1000],
        1100: colors.primary[1100],
        1200: colors.primary[1200],
        1300: colors.primary[1300],
      },
      green: {
        100: colors.green[100],
        200: colors.green[200],
        300: colors.green[300],
        400: colors.green[400],
        500: colors.green[500],
        600: colors.green[600],
        700: colors.green[700],
        800: colors.green[800],
        900: colors.green[900],
        1000: colors.green[1000],
        1100: colors.green[1100],
        1200: colors.green[1200],
      },
      red: {
        100: colors.red[100],
        200: colors.red[200],
        300: colors.red[300],
        400: colors.red[400],
        500: colors.red[500],
        600: colors.red[600],
        700: colors.red[700],
        800: colors.red[800],
        900: colors.red[900],
        1000: colors.red[1000],
        1100: colors.red[1100],
        1200: colors.red[1200],
      },
      yellow: {
        100: colors.yellow[100],
        200: colors.yellow[200],
        300: colors.yellow[300],
        400: colors.yellow[400],
        500: colors.yellow[500],
        600: colors.yellow[600],
        700: colors.yellow[700],
        800: colors.yellow[800],
        900: colors.yellow[900],
        1000: colors.yellow[1000],
        1100: colors.yellow[1100],
        1200: colors.yellow[1200],
      },
      supportColor: {
        "01": colors.supportColor["01"],
        "02": colors.supportColor["02"],
        "03": colors.supportColor["03"],
        "04": colors.supportColor["04"],
        "05": colors.supportColor["05"],
      },
      shades: {
        0: colors.shades[0],
        100: colors.shades[100],
      },
      linear: {
        0: colors.linear[0],
      },
    },
    screens: {
      "3xl": { max: "2560px" },
      // => @media (max-width: 2560px) { ... }

      "2xl": { max: "1440px" },
      // => @media (max-width: 1440px) { ... }

      xl: { max: "1280px" },
      // => @media (max-width: 1280px) { ... }

      lg: { max: "1184px" },
      // => @media (max-width: 1184px) { ... }

      md: { max: "1024px" },
      // => @media (max-width: 1024px) { ... }

      sm: { max: "768px" },
      // => @media (max-width: 600px) { ... }

      xs: { max: "450px" },
      // => @media (max-width: 450px) { ... }

      "2xs": { max: "425px" },
      // => @media (max-width: 450px) { ... }

      "3xs": { max: "375px" },
      // => @media (max-width: 450px) { ... }
    },
    fontSize: {
      regular10: ["10px", { lineHeight: "12px", fontWeight: "400" }],
      medium10: ["10px", { lineHeight: "12px", fontWeight: "500" }],
      semiBold10: ["10px", { lineHeight: "12px", fontWeight: "600" }],
      bold10: ["10px", { lineHeight: "12px", fontWeight: "700" }],
      regular11: ["11px", { lineHeight: "16px", fontWeight: "400" }],
      regular12: ["12px", { lineHeight: "18px", fontWeight: "400" }],
      medium12: ["12px", { lineHeight: "18px", fontWeight: "500" }],
      bold12: ["12px", { lineHeight: "18px", fontWeight: "700" }],
      regular13: ["13px", { lineHeight: "20px", fontWeight: "400" }],
      medium13: ["13px", { lineHeight: "20px", fontWeight: "500" }],
      semiBold13: ["13px", { lineHeight: "20px", fontWeight: "600" }],
      bold13: ["13px", { lineHeight: "20px", fontWeight: "700" }],
      regular14: ["14px", { lineHeight: "20px", fontWeight: "400" }],
      regularQuicksan14: ["14px", { lineHeight: "17.5px", fontWeight: "400" }],
      medium14: ["14px", { lineHeight: "20px", fontWeight: "500" }],
      semiboldQuicksan14: ["14px", { lineHeight: "17.5px", fontWeight: "600" }],
      semiBold14: ["14px", { lineHeight: "20px", fontWeight: "700" }],
      bold14: ["14px", { lineHeight: "20px", fontWeight: "700" }],
      regular15: ["15px", { lineHeight: "24px", fontWeight: "400" }],
      regular16: ["16px", { lineHeight: "24px", fontWeight: "400" }],
      medium16: ["16px", { lineHeight: "26px", fontWeight: "500" }],
      mediumQuicksan16: ["16px", { lineHeight: "20px", fontWeight: "500" }],
      semiBold16: ["16px", { lineHeight: "26px", fontWeight: "600" }],
      bold16: ["16px", { lineHeight: "26px", fontWeight: "700" }],
      semiBold17: ["17px", { lineHeight: "26px", fontWeight: "600" }],
      regular18: ["18px", { lineHeight: "28px", fontWeight: "400" }],
      medium18: ["18px", { lineHeight: "28px", fontWeight: "500" }],
      semiBold18: ["18px", { lineHeight: "28px", fontWeight: "600" }],
      bold18: ["18px", { lineHeight: "28px", fontWeight: "700" }],
      regular20: ["20px", { lineHeight: "29px", fontWeight: "400" }],
      medium20: ["20px", { lineHeight: "28px", fontWeight: "500" }],
      semiBold20: ["20px", { lineHeight: "28px", fontWeight: "600" }],
      bold20: ["20px", { lineHeight: "28px", fontWeight: "700" }],
      extraBold20: ["20px", { lineHeight: "28px", fontWeight: "800" }],
      semiBold22: ["22px", { lineHeight: "32px", fontWeight: "600" }],
      regular22: ["22px", { lineHeight: "32px", fontWeight: "400" }],
      regular24: ["24px", { lineHeight: "24px", fontWeight: "400" }],
      medium24: ["24px", { lineHeight: "32px", fontWeight: "500" }],
      semiBold24: ["24px", { lineHeight: "30px", fontWeight: "600" }],
      bold24: ["24px", { lineHeight: "25px", fontWeight: "700" }],
      extraBold24: ["24px", { lineHeight: "50px", fontWeight: "800" }],
      regular28: ["28px", { lineHeight: "36px", fontWeight: "400" }],
      medium28: ["28px", { lineHeight: "36px", fontWeight: "500" }],
      semiBold28: ["28px", { lineHeight: "36px", fontWeight: "600" }],
      bold28: ["28px", { lineHeight: "36px", fontWeight: "700" }],
      extraBold28: ["28px", { lineHeight: "50px", fontWeight: "800" }],
      semibold28: ["28px", { lineHeight: "36px", fontWeight: "600" }],
      regular32: ["32px", { lineHeight: "40px", fontWeight: "400" }],
      regularAmoera32: ["32px", { lineHeight: "35px", fontWeight: "400" }],
      medium32: ["32px", { lineHeight: "40px", fontWeight: "500" }],
      semibold32: ["32px", { lineHeight: "34px", fontWeight: "600" }],
      bold32: ["32px", { lineHeight: "40px", fontWeight: "700" }],
      semiBold36: ["36px", { lineHeight: "44px", fontWeight: "600" }],
      regular36: ["36px", { lineHeight: "44px", fontWeight: "400" }],
      medium36: ["36px", { lineHeight: "44px", fontWeight: "500" }],
      bold36: ["36px", { lineHeight: "44px", fontWeight: "700" }],
      extraBold36: ["36px", { lineHeight: "44px", fontWeight: "800" }],
      regular40: ["40px", { lineHeight: "56px", fontWeight: "400" }],
      semiBold40: ["40px", { lineHeight: "48px", fontWeight: "600" }],
      bold40: ["40px", { lineHeight: "56px", fontWeight: "700" }],
      extraBold40: ["40px", { lineHeight: "56px", fontWeight: "800" }],
      regular48: ["48px", { lineHeight: "72px", fontWeight: "400" }],
      medium48: ["48px", { lineHeight: "72px", fontWeight: "500" }],
      semiBold48: ["48px", { lineHeight: "72px", fontWeight: "600" }],
      bold48: ["48px", { lineHeight: "72px", fontWeight: "700" }],
      regular60: ["60px", { lineHeight: "90px", fontWeight: "400" }],
      medium60: ["60px", { lineHeight: "90px", fontWeight: "500" }],
      bold60: ["60px", { lineHeight: "90px", fontWeight: "700" }],
      regular70: ["70px", { lineHeight: "108px", fontWeight: "400" }],
      medium70: ["70px", { lineHeight: "108px", fontWeight: "500" }],
      bold70: ["70px", { lineHeight: "108px", fontWeight: "700" }],
    },
  },
  plugins: [
    require("@tailwindcss/typography"),
    require("@tailwindcss/line-clamp"),
  ],
};
export default config;
