import colors from "../../styles/colors";

const colorsApp = {
  content: {
    primary: colors.neutral[1200],
    secondary: colors.neutral[1000],
    tertiary: colors.neutral[800],
    primaryInverse: colors.neutral.white,
    secondaryInverse: colors.neutral[300],
    tertiaryInverse: colors.neutral[200],
    disabled: colors.neutral[500],
    brand: colors.primary[900],
    link: colors.primary[900],
    linkHover: colors.primary[1100],
    notice: colors.yellow[800],
    noticeSecondary: colors.yellow[200],
    noticeBold: colors.yellow[1000],
    negative: colors.red[800],
    negativeSecondary: colors.red[200],
    negativeBold: colors.red[1000],
    positive: colors.green[800],
    positiveSecondary: colors.green[200],
    positiveBold: colors.green[1000],
  },
  background: {
    bg: colors.neutral.white,
    bgInverse: colors.primary[1100],
    bgSideBar: colors.neutral[1200],
  },
  surface: {
    primary: colors.neutral.white,
    transparent: colors.neutralAlpha[1000],
    transparentSecondary: colors.neutralAlpha[700],
    primaryInverse: colors.neutral[1200],
    primaryHover: colors.neutral[100],
    primaryActive: colors.neutral[200],
    primaryDisabled: colors.neutral[300],
    primarySelected: colors.primary[400],
    secondary: colors.neutral[100],
    secondaryInverse: colors.neutral[1000],
    secondaryHover: colors.neutral[200],
    secondaryActive: colors.primary[200],
    secondaryDisabled: colors.neutral[300],
    secondarySelected: colors.primary[400],
    tertiary: colors.neutral[300],
    tertiaryHover: colors.neutral[400],
    tertiaryActive: colors.primary[200],
    tertiaryDisabled: colors.neutral[400],
    tertiarySelected: colors.primary[300],
    brand: colors.primary[900],
    brandSecondary: colors.primary[300],
    brandHover: colors.primary[1000],
    brandActive: colors.primary[900],
    brandDisabled: colors.neutral[500],
    link: colors.primary[900],
    linkHover: colors.primary[1100],
    linkActive: colors.primary[1100],
    linkDisabled: colors.neutral[300],
    linkSelected: colors.primary[400],
    notice: colors.yellow[700],
    noticeSecondary: colors.yellow[200],
    noticeHover: colors.yellow[900],
    noticeActive: colors.yellow[800],
    noticeDisabled: colors.neutral[300],
    negative: colors.red[800],
    negativeSecondary: colors.red[200],
    negativeHover: colors.red[1000],
    negativeActive: colors.red[900],
    negativeDisabled: colors.neutral[500],
    positive: colors.green[800],
    positiveSecondary: colors.green[200],
    positiveHover: colors.green[1000],
    positiveActive: colors.green[900],
    positiveDisabled: colors.neutral[500],
  },
  border: {
    primary: colors.neutral[300],
    primaryHover: colors.neutral[400],
    primaryActive: colors.primary[700],
    primaryDisabled: colors.neutral[500],
    primarySelected: colors.primary[700],
    secondary: colors.neutral[200],
    secondaryHover: colors.neutral[400],
    secondaryActive: colors.primary[700],
    secondaryDisabled: colors.neutral[500],
    secondarySelected: colors.primary[700],
    tertiary: colors.neutral[300],
    tertiaryHover: colors.neutral[400],
    tertiaryActive: colors.primary[700],
    tertiaryDisabled: colors.neutral[500],
    tertiarySelected: colors.primary[700],
    brand: colors.primary[900],
    brandHover: colors.primary[1100],
    brandActive: colors.primary[900],
    brandDisabled: colors.primary[500],
    notice: colors.yellow[700],
    noticeHover: colors.yellow[900],
    noticeActive: colors.yellow[800],
    noticeDisabled: colors.neutral[500],
    negative: colors.red[800],
    negativeHover: colors.red[1000],
    negativeActive: colors.red[900],
    negativeDisabled: colors.red[500],
    positive: colors.green[800],
    positiveHover: colors.green[1000],
    positiveActive: colors.green[900],
    positiveDisabled: colors.green[500],
  },
  transparent: {
    bgPopup: colors.neutralAlpha[600],
  },
};

export default colorsApp;
